FROM quay.io/fedora/fedora-coreos:stable

ARG KUBESOLO_VERSION=v1.2.1
ARG FLUX_VERSION=v2.9.6
ARG KUBECTL_VERSION=v1.35.9
ARG CRICTL_VERSION=v1.35.0
# у Oh My Zsh нет релизов, версия закреплена коммитом
ARG OMZ_COMMIT=60c9a7a839b790cd905d0fd4419435124fd1bdc0

RUN dnf install -y --setopt=install_weak_deps=False \
        flatpak \
        fedora-flathub-remote \
        cockpit \
        cockpit-system \
        cockpit-networkmanager \
        cockpit-storaged \
        NetworkManager-ppp \
        ppp \
        samba \
        nfs-utils \
        fail2ban \
        vim \
        firewalld \
        wget \
        zsh \
        zsh-autosuggestions \
        zsh-syntax-highlighting \
        alsa-utils \
        rclone \
        alsa-firmware \
        alsa-sof-firmware \
        s3fs-fuse \
        htop \
        mc \
        atop \
        btop \
        fuse \
        ncdu \
        strace \
        tcpdump \
        traceroute \
        mtr \
        iotop-c \
        sysstat \
        conntrack-tools \
        nmap-ncat \
        tmux \
        git \
        usbutils \
        iftop \
        nethogs \
        iperf3 \
        fio \
        tree \
        unzip \
        lshw \
        dmidecode \
        smartmontools \
        lm_sensors && \
    dnf clean all && \
    ostree container commit

COPY podman/registries.conf /etc/containers/registries.conf

COPY samba/smb.conf /etc/samba/smb.conf

COPY --chmod=600 s3/passwd-s3fs /etc/passwd-s3fs
COPY s3/var-mnt-s3.mount /etc/systemd/system/var-mnt-s3.mount

COPY nfs/exports /etc/exports

COPY firewall/trusted.xml /etc/firewalld/zones/trusted.xml
COPY firewall/public.xml /etc/firewalld/zones/public.xml

RUN systemctl enable \
        smb.service nfs-server.service cockpit.socket var-mnt-s3.mount firewalld.service fail2ban.service && \
        ostree container commit

# KubeSolo
RUN curl -fsSL -o /tmp/kubesolo.tar.gz \
      "https://github.com/portainer/kubesolo/releases/download/${KUBESOLO_VERSION}/kubesolo-${KUBESOLO_VERSION}-linux-amd64.tar.gz" && \
    tar -xzf /tmp/kubesolo.tar.gz -C /tmp && \
    install -m 0755 /tmp/kubesolo /usr/bin/kubesolo && \
    rm -rf /tmp/kubesolo*

#kubectl и flux CLI
RUN curl -fsSL -o /usr/bin/kubectl \
      "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod 0755 /usr/bin/kubectl && \
    curl -fsSL "https://github.com/fluxcd/flux2/releases/download/${FLUX_VERSION}/flux_${FLUX_VERSION#v}_linux_amd64.tar.gz" \
      | tar -xz -C /usr/bin flux

# crictl (сокет containerd KubeSolo: /var/lib/kubesolo/containerd/containerd.sock)
RUN curl -fsSL "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" \
      | tar -xz -C /usr/bin crictl

#Flux
RUN mkdir -p /usr/share/homeserver/flux && \
    curl -fsSL -o /usr/share/homeserver/flux/install.yaml \
      "https://github.com/fluxcd/flux2/releases/download/${FLUX_VERSION}/install.yaml"

# zsh + Oh My Zsh
RUN mkdir -p /usr/share/oh-my-zsh && \
    curl -fsSL "https://github.com/ohmyzsh/ohmyzsh/archive/${OMZ_COMMIT}.tar.gz" \
      | tar -xz --strip-components=1 -C /usr/share/oh-my-zsh

COPY fail2ban/sshd.local /etc/fail2ban/jail.d/sshd.local
COPY --chmod=600 ssh/01-hardening.conf /etc/ssh/sshd_config.d/01-hardening.conf
COPY zsh/zshrc /etc/skel/.zshrc
COPY zsh/core-shell.service /usr/lib/systemd/system/core-shell.service

COPY --chmod=600 k8s/kubesolo-config.yaml /etc/kubesolo/config.yaml
COPY k8s/kubesolo.service /usr/lib/systemd/system/kubesolo.service
COPY k8s/flux-sync.yaml /usr/share/homeserver/flux/flux-sync.yaml
COPY k8s/flux-bootstrap.service /usr/lib/systemd/system/flux-bootstrap.service

RUN systemctl enable kubesolo.service flux-bootstrap.service core-shell.service && \
    ostree container commit