---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mopidy
  name: mopidy
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  containers:
  - image: ghcr.io/fedextm/mopidy:v3.0.2
    name: mopidy
    resources:
      limits:
        memory: 512Mi
        cpu: "500m"
      requests:
        memory: 256Mi
        cpu: "250m"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      fsGroup: 1000
    volumeMounts:
    - mountPath: /music
      name: mp-music-0
    - mountPath: /config
      name: mp-config-0
  hostNetwork: true
  hostUsers: true
  hostname: mopidy.localhost
  volumes:
  - hostPath:
      path: /var/mnt/data/music
      type: Directory
    name: mp-music-0
  - hostPath:
      path: /var/mnt/data/containers_data/mopidy/config
      type: Directory
    name: mp-config-0
