variant: fcos
version: 1.6.0
kernel_arguments:
  should_exist:
    - mitigations=off
    - net.ifnames=0 
    - biosdevname=0  
    - selinux=0  
    - audit=0
  should_not_exist:
    - mitigations=auto,nosmt
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDerW5/oq90/fUprncOcLmQL4iuKP06d9PsGdmVBAwpcZYayyW3/or5Q6eFgAmEOfQEpKiB2NgUb8FOjhAzp9TdG/TAODRSZ2IWkov7HoFC5yzwfC+hoh01v3ioBFO0wioPC3aT6IQg7w6i3bq0vktdhhP/8lvodgKuU39UTLnD4ftJ/BB4ZIAoJySI4ce5OMulZZr79RLhsQwrm7FFb+zTPc4OpGIe0VRgynHXadCpjGQaEEP26S9Pbzi0vNxGVCPjUMbEvVU244M3ZI2PFu6Y8eBBVyeFIKcavGgwPHwzHTXZjwjZsz1P2yo1T5qsv2H5sOBvGiPda+b3J0b6Z5DYRAaGWf5oMJ1xn/Jasr/0hU2SNBwfN9Sl/qZ+GPSeFZSjqAa1t5r8fFwnifX3rVrlbk2v6YShK02IjZQ/YRmfZ7kbybchop2Sml8hmBH2686fGlOTL5/aC4py0HM25Dqj8sJNydPO4f+OzN7QtXIPlcw0mjVhxifz4IiXLpbhwI8= fed@localhost.localdomain
      password_hash: $y$j9T$KBYCUm.3CT4/GE.MH0bWi/$ld9p.8ZzLBFRBhhde7RmKCtOvRlxl1NwyteIADPZij/
    - name: plex
      shell: /sbin/nologin    
      home_dir: /var/mnt/data/containers_data/plex/plexmediaserver
systemd:
  units:
    - name: systemd-resolved.service
      enabled: false
    - name: rebase.service
      enabled: true
      contents: |
        [Unit]
        Description=Rebase to mediabarn-image
        ConditionFirstBoot=true
        After=network-online.target
        
        [Install]
        WantedBy=default.target

        [Service]
        After=ignition-firstboot-complete.service
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/bin/sleep 30
        ExecStartPre=systemctl disable zincati
        ExecStart=rpm-ostree rebase --bypass-driver --reboot ostree-unverified-registry:ghcr.io/fedextm/homeserver:v0.6
        ExecStartPost=/usr/bin/chown 1000:1000 /var/mnt/data
        ExecStartPost=/usr/bin/usermod -s /usr/bin/zsh core
        WantedBy=multi-user.target
    - name: var-mnt-data.mount
      enabled: true
      contents: |
        [Unit]
        Description=Mount Data Volume
        
        [Mount]
        What=/dev/mapper/vg_data-lv_data
        Where=/var/mnt/data
        Type=ext4
        Options=nofail,noatime,discard,errors=remount-ro

        [Install]
        WantedBy=multi-user.target
storage:
    links:
      - path: /etc/localtime
        target: ../usr/share/zoneinfo/Europe/Warsaw
    directories:
      - path: /var/mnt/data
        mode: 0777
        user:
          name: core
        group:
          name: core
    files:
      - path: /etc/resolv.conf
        mode: 0644
        contents:
          inline: |
            # Generated by NetworkManager
            search lan
            nameserver 192.168.3.201
      - path: /etc/systemd/zram-generator.conf
        mode: 0644
        contents:
          inline: |
            # This config file enables a /dev/zram0 device with the default settings
            [zram0]
      - path: /var/lib/systemd/linger/core
        mode: 0644
      - path: /etc/ostree/auth.json
        mode: 0600
        contents: 
          local: auth.json
      - path: /etc/hostname
        mode: 0644
        contents:
          inline: homeserver.local
      - path: /etc/sysctl.d/90-ipfw.conf
        contents:
          inline: |
            net.ipv4.ip_forward = 1
      - path: /etc/NetworkManager/system-connections/eth0.nmconnection
        mode: 0600
        contents:
          inline: |
            [connection]
            id=eth0
            type=ethernet
            interface-name=eth0
            zone=public
            [ipv4]
            address1=192.168.122.3/24
            method=manual
            [ipv6]
            addr-gen-mode=default
            method=disabled
      - path: /etc/NetworkManager/system-connections/eth1.nmconnection
        mode: 0600
        contents:
          inline: |
            [connection]
            id=eth1
            type=ethernet
            interface-name=eth1
            zone=trusted
            [ipv4]
            address1=192.168.250.3/24
            dns=192.168.3.201;
            gateway=192.168.250.1
            method=manual
            [ipv6]
            addr-gen-mode=default
            method=disabled

