apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: caddy-config
    namespace: caddy
    files:
      - Caddyfile
