[global]
   min protocol = SMB2
   ntlm auth = ntlmv1-permitted
   server role = standalone server
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   log level = 1
   panic action = /usr/share/samba/panic-action %d
   map to guest = bad user
   vfs objects = catia fruit streams_xattr
   fruit:model = MacSamba
   fruit:metadata = stream
   fruit:veto_appledouble = no
   fruit:nfs_aces = no
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes
   fruit:posix_rename = yes
   server min protocol = SMB2

[TimeMachine]
  path = /var/mnt/data/backup/timemachine
  read only = no
  browseable = yes
  writeable = yes
  guest ok = yes
  fruit:time machine = yes
  create mask = 0777
  directory mask = 0777
  force user = core
  force group = core

[hdd-disk]
   comment = External Seagate hard drive
   read only = no
   path = /var/mnt/data
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   force user = core
   force group = core
