apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: monitoring
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: prometheus
      port: 9092
      targetPort: 9090
