---
variant: fcos
version: 1.7.0
kernel_arguments:
  should_exist:
    - mitigations=off
    - net.ifnames=0
    - biosdevname=0
    - selinux=0
    - audit=0
  should_not_exist:
    - mitigations=auto,nosmt
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        # yamllint disable-line rule:line-length
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMrhzLZ8O4hgoTCsZMrrJPsCPmdK6qkBjdSgbCc8YPXi fed@localhost.localdomain
      password_hash: $y$j9T$KBYCUm.3CT4/GE.MH0bWi/$ld9p.8ZzLBFRBhhde7RmKCtOvRlxl1NwyteIADPZij/
    - name: plex
      uid: 1001
      primary_group: plex
      shell: /sbin/nologin
      no_create_home: true
  groups:
    - name: plex
      gid: 1001
systemd:
  units:
    # - name: actions-runner.service
    #   enabled: true
    #   contents_local: actions-runner.service
    - name: zincati.service
      enabled: false
    - name: podman-restart.service
      enabled: true
    - name: systemd-resolved.service
      enabled: false
    # - name: rebase.service
    #   enabled: true
    #   contents_local: rebase.service
    - name: var-mnt-data.mount
      enabled: true
      contents_local: data.mount
    - name: var-mnt-mirror.mount
      enabled: true
      contents_local: mirror.mount
    # Only for testing
    # - name: var-mnt-data.mount
    #   enabled: true
    #   contents_local: data-test.mount
storage:
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/Europe/Warsaw
  directories:
    - path: /var/mnt/data
    - path: /var/mnt/mirror
  files:
    - path: /etc/systemd/journald.conf
      mode: 0644
      overwrite: true
      contents:
        local: journald.conf
    - path: /etc/resolv.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          # Uploaded from ignition
          search lan
          nameserver 8.8.8.8
    - path: /etc/NetworkManager/conf.d/90-dns-none.conf
      mode: 0644
      contents:
        local: nm/90-dns-none.conf
    - path: /etc/systemd/zram-generator.conf
      mode: 0644
      contents:
        inline: |
          # This config file enables a /dev/zram0 device with the default settings
          [zram0]
    - path: /var/lib/systemd/linger/core
      mode: 0644
    - path: /etc/ostree/auth.json
      mode: 0600
      contents:
        local: .auth.json
    - path: /etc/hostname
      mode: 0644
      overwrite: true
      contents:
        inline: |
          homeserver.local
    - path: /etc/sysctl.d/90-ipfw.conf
      contents:
        inline: |
          net.ipv4.ip_forward = 1
    - path: /etc/NetworkManager/system-connections/eth0.nmconnection
      mode: 0600
      contents:
        local: nm/eth0.nmconnection
    - path: /etc/NetworkManager/system-connections/eth1.nmconnection
      mode: 0600
      contents:
        local: nm/eth1.nmconnection
