apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: transmission-settings
    namespace: transmission
    files:
      - settings.json
