apiVersion: v1
kind: Secret
metadata:
    name: pihole-web
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xT4q,iv:ZxtaqwN1SHImK7V5TMltu/zJ9REmXxTj6Ze4iIhxj+M=,tag:KdO5uwQv7CHVy0S26z71qg==,type:str]
sops:
    age:
        - recipient: age1wmaqsl2clakvn6w6eef6c8x8djw9ktsnsj9zl92f9r250esugqjqehqfv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cUUyazladkpmSHhKTWRx
            b2ZlT1R1b2l5dWJPVm9EV3M5bU9wN0tQTW00CkZWaGFZdFBnc2h4YzZYQVhjQkdj
            V29mWkt1UkttNGZIWXZOUzhqLzlPWEEKLS0tIHRvQmJyVkszbStFU1JXK1NiTkZp
            bDE0N3hDc1FiYWxxamVKVmlteTlqY2MKgk9A36eVNhR/d1GfMGOqc6/qFsglAeKm
            5julwfpOwCGGEHKYx/oYTl9g7soSHBjfXtCNc6FQiWM6cw4guJrcnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T14:58:33Z"
    mac: ENC[AES256_GCM,data:+6kFbQmrk6IB3nF3RaJX6HCQ6NPiLlShwPJUqMWqheluT1vR9UmM7Ek6uw0fN0M7EyPapnKzahmeNso/ja9tXfhqylMqXNja49QC9HcWgtPLOuM5ct2q8qMBDjBd1A/Smg3kY/sthS7f6yQZiHYF3bWjsqp7vmOHPPmo/Vh1D60=,iv:CGeehvsSOAn6twXYJDCOuwP+R8JG6rhBjYt2O9/1oSQ=,tag:ptjuTkOIjj3uGAt76oyOYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
