apiVersion: v1
kind: Secret
metadata:
    name: pihole-web
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Atuv6JRW74XCAzsBbnouu906T4M=,iv:3Adhs551IWpGOH+5Moc46WnC078bwPWVI2qtU8ij/gI=,tag:RK46pVeiFYUantA2yVge8A==,type:str]
sops:
    age:
        - recipient: age1wmaqsl2clakvn6w6eef6c8x8djw9ktsnsj9zl92f9r250esugqjqehqfv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cUUyazladkpmSHhKTWRx
            b2ZlT1R1b2l5dWJPVm9EV3M5bU9wN0tQTW00CkZWaGFZdFBnc2h4YzZYQVhjQkdj
            V29mWkt1UkttNGZIWXZOUzhqLzlPWEEKLS0tIHRvQmJyVkszbStFU1JXK1NiTkZp
            bDE0N3hDc1FiYWxxamVKVmlteTlqY2MKgk9A36eVNhR/d1GfMGOqc6/qFsglAeKm
            5julwfpOwCGGEHKYx/oYTl9g7soSHBjfXtCNc6FQiWM6cw4guJrcnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T14:28:25Z"
    mac: ENC[AES256_GCM,data:TnyI3WFSniMoxs6Iu5pV+fLkkBhr1Cj0jLkxh+qG0mlEk2gyyibdMmZGFAfg4TI1YE3PFVcsWjHjn/jneJQL7kVxRHXDyutL+f4Zi85yi6IUQDw+IC5H/0ZtTpjjZ2F3xBl/Lvzyh5il5Cjk5mj9zgT5ilbbggv+5lmeiFH5nS4=,iv:rMwdSsXqMzoepJtBEWsWkpQsONgcqQGad9bKSsga0GM=,tag:RRjv0oCwJHS4AvIzx3Wscg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
