# Files and directories #######################################################
music_directory	   "/music"
playlist_directory "/music/playlists"
db_file			   "/config/database"
log_file		   "/config/mpd.log"
pid_file		   "/config/mpd.pid"
state_file		   "/config/state"
sticker_file	   "/config/sticker.sql"

# General music daemon options ################################################
bind_to_address		"0.0.0.0"
port				"6600"
log_level			"info"
metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update	"yes"

# Symbolic link behavior ######################################################
follow_outside_symlinks	"yes"
follow_inside_symlinks		"yes"

# Zeroconf / Avahi Service Discovery ##########################################
zeroconf_enabled		"no"

# Database #######################################################################
audio_buffer_size   "24384"

# Audio Output ################################################################
audio_output {
	type		"alsa"
	name		"Emotiva BasX TA1"
	device		"hw:0"	# "hw:SXWP32768M4549"
        auto_resample   "no"
        auto_channels   "no"
        auto_format     "no"
        dop             "yes"
	mixer_type      "hardware"
        buffer_time     "1500000"
        period_time     "80000"
}

audio_output {
	type		"httpd"
	name		"Foxy Stream"
	encoder		"vorbis"		# optional, vorbis or lame
	port		"8000"
	bind_to_address	"0.0.0.0"		# optional, IPv4 or IPv6
	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"320"			# do not define if quality is defined
#	format		"44100:16:1"
	max_clients	"0"			# optional 0=no limit
	always_on       "yes"
	#tags        "yes"
}

# Normalization automatic volume adjustments ##################################
replaygain			      "off"
replaygain_preamp		  "-6"
replaygain_missing_preamp "0"
replaygain_limit		  "yes"
volume_normalization	  "no"
max_output_buffer_size    "16384"

# Character Encoding ##########################################################
filesystem_charset		"UTF-8"
decoder {
       plugin                   "wildmidi"
       enabled                  "no"
       config_file              "/config/timidity.cfg"
}

decoder {
    plugin "ffmpeg"
    enabled "yes"
}

decoder {
    plugin "mpg123"
    enabled "no"
}
