apiVersion: v1
kind: Service
metadata:
  name: mpd
  namespace: mpd
spec:
  type: LoadBalancer
  selector:
    app: mpd
  ports:
    - name: mpd
      port: 6600
      targetPort: 6600
    - name: http
      port: 8000
      targetPort: 8000
      