apiVersion: kubesolo.io/v1alpha1
kind: Config

path: /var/lib/kubesolo

kubernetes:
  apiServer:
    extraSANs:
      - 192.168.3.201
      - homeserver.local

network:
  nodeIP: 192.168.3.201

storage:
  localPath:
    enabled: true
  dbWALRepair: true
