apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mpd
  - plex
  - transmission
  - pihole
  - backup
  - vault
  - monitoring
  - node-exporter
  # Temporarily disabled due to high resource usage 
  # - cadvisor
  # - kube-state-metrics
  - calibre-web
