# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-25T14:46:34Z"
  labels:
    app: transmission-pod
  name: transmission-pod
  annotations:
    io.podman.annotations.userns: "keep-id" 
spec:
  containers:
  - image: ghcr.io/fedextm/transmission:v4.0.6
    name: transmission
    resources:
      limits:
        memory: 512Mi
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      fsGroup: 1000
    volumeMounts:
    - mountPath: /config
      name: tr-config-0
    - mountPath: /data
      name: tr-data-0
  hostNetwork: true
  hostUsers: true
  hostname: transmission.localhost
  volumes:
  - hostPath:
      path: /var/mnt/data/containers_data/transmission/config
      type: Directory
    name: tr-config-0
  - hostPath:
      path: /var/mnt/data
      type: Directory
    name: tr-data-0

