apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.hcl: |
    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true
    }

    api_addr          = "http://192.168.3.201:8200"
    ui                = true
    disable_mlock     = true
    default_lease_ttl = "168h"
    max_lease_ttl     = "720h"
    