apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vault
          image: docker.io/hashicorp/vault:2.1.1
          args: ["server"]
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: SKIP_SETCAP
              value: "true"
          ports:
            - name: http
              containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
              port: 8200
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
              port: 8200
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"            
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          hostPath:
            path: /var/mnt/data/ct_data/vault/data
            type: Directory
