---
name: Build Image

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["pre-commit"]
    types:
      - completed
    paths:
      - 'Containerfile'
      - 'mopidy/**'
      - 'plex/**'
      - 'pihole/**'
      - 'samba/**'
      - 'podman/**'
      - 'sound/**'
      - 'transmission/**'
      - 'nfs/**'

jobs:
  build:
    name: Build Image
    runs-on: [self-hosted, Linux]  # Uses your private runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image with Podman
        run: |
          podman build --volume /var/mnt/data:/data -t fedextm/homeserver:latest -f ./Containerfile .
