name: Build and Push Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Image
    runs-on: [self-hosted, Linux] # Uses your private runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image with Podman
        run: |
          podman build --volume /var/mnt/data:/data -t local/fedextm/homeserver:default -f ./Containerfile .
